server:
  port: 8084

spring:
  application:
    name: client-feign

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
feign:
  hystrix:
    #¿ªÆô¶ÏÂ·Æ÷
    enabled: true
